sudo: required

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - mongodb
  - rabbitmq
  - memcached
  - docker

script: sbt ++$TRAVIS_SCALA_VERSION test:compile &&
    sbt ++$TRAVIS_SCALA_VERSION "gloseval/run gencert --self-signed" &&
    sbt ++$TRAVIS_SCALA_VERSION gloseval/docker:publishLocal 

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis-ci" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag synereo/base:latest sgov74/synereo:travis-$TRAVIS_BUILD_NUMBER;
    docker push sgov74/synereo:travis-$TRAVIS_BUILD_NUMBER;
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0be5e8019da24eb59119
    on_success: change
    on_failure: always
    on_start: never

